### ISSUE TITLE
Question - where did you get your project ideas from?

### ISSUE THREAD

**Issue by schaveyt** [bonham000/25-react-projects#1]
Sean, I'd your idea of working throufots of small project. Where did you get your list from?

**Comment by bonham000** [comment]
@schaveyt most of the ideas came from freeCodeCamp:

Projects 11 - 18 are the freeCodeCamp Front End projects
Projects 21 - 25 are the current freeCodeCamp React project

The inspiration for the entire thing was originally reaching the freeCodeCamp React projects and really struggling with them (there was no FCC React curriculum at the time, [now there is](http://hysterical-amusement.surge.sh/).

The rest of the project ideas were just very simple things that I came up with on my own and built. Most of them were things that I had some kind of interest in building, but the point was to just repeatedly practice basic/intermediate projects in order to develop a strong foundation in React.

**Comment by schaveyt** [comment]
Haha. Brillant. Thx for share this!
